site_name: IHC - Grupo 4
site_author: Ana, Anne, José e Pedro
site_description: Site voltado para a documentação do Grupo 4 sobre Interação Humano-Computador
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo04
repo_name: 2024.2-Grupo04

nav:
  - Sobre: index.md
  - Planejamento:
    - "Cronograma": planejamento/cronograma.md
    - "Sites Avaliados": planejamento/sites-avaliados.md
    - "Ferramentas": planejamento/ferramentas.md
  - "Verificações":
    - "Entrega 1":
      - "Lista de verificação": avaliacoes/entrega1/avaliacao.md
      - "Lista de verificação grupo 5": avaliacoes/entrega1/avaliacao+1.md

  - "Atas":
    - "Ata 1": atas/ata1.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  disable_nav_previous_next: true

  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Trocar para modo escuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Trocar para modo claro

  favicon: assets/cinemark-icon.png
  logo: assets/cinemark-icon.png
  

markdown_extensions:
  - tables
  - attr_list
  - md_in_html


extra_css: [stylesheets/extra.css]