site_name: IHC - Grupo 4
site_description: Site voltado para a documentação do Grupo 4 
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo04
repo_name: 2024.2-Grupo04



theme:
  name: null
  custom_dir: 'cinder'
  color_mode: auto
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - "Entregas":
    - "Entrega 1": entregas/entrega1.md
  - "Verificações":
    - "Verificação 1": avaliacoes/avaliacao1.md
  - "Atas": 
    - "Reunião 1": Atas/ata1.md

markdown_extensions:
  - tables