site_name: IHC - Grupo 4
site_author: Ana, Anne, José e Pedro
site_description: Site voltado para a documentação do Grupo 4 sobre Interação Humano-Computador
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Cinemark
repo_name: 2024.2-Cinemark

nav:
  - Sobre: index.md

  - Verificações:
      - "Entrega 1":
          - "Lista de verificação": avaliacoes/entrega1/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega1/avaliacao+1.md
      - "Entrega 2":
          - "Lista de verificação": avaliacoes/entrega2/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega2/avaliacao+1.md
      - "Entrega 3":
          - "Lista de verificação": avaliacoes/entrega3/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega3/avaliacao+1.md
      - "Entrega 4":
          - "Lista de verificação": avaliacoes/entrega4/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega4/avaliacao+1.md
      - "Entrega 5":
          - "Lista de verificação": avaliacoes/entrega5/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega5/avaliacao+1.md
      - "Entrega 6":
          - "Lista de verificação": avaliacoes/entrega6/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega6/avaliacao+1.md
      - "Entrega 7":
          - "Lista de verificação": avaliacoes/entrega7/avaliacao.md
          - "Lista de verificação grupo 5": avaliacoes/entrega7/avaliacao+1.md
      - "Entrega 8":
          - "Lista de verificação dos artefatos do grupo":
             - "Personas": avaliacoes/entrega8/verificacao/personas.md
             - "Elenco de Personas": avaliacoes/entrega8/verificacao/elenco-de-personas.md
             - "Cenários": avaliacoes/entrega8/verificacao/cenarios.md         
             - "Análise de Hierárquia de Tarefas": avaliacoes/entrega8/verificacao/hta.md
             - "Árvores de Tarefas Concorrentes": avaliacoes/entrega8/verificacao/ctt.md
             - "Framework DECIDE": 
                - "Análise de Hierárquia de Tarefas": avaliacoes/entrega8/verificacao/DECIDE/hta.md
                - "Storyboard": avaliacoes/entrega8/verificacao/DECIDE/storyboard.md               
                - "Protótipo de Papel": avaliacoes/entrega8/verificacao/DECIDE/proto-papel.md
                - "Protótipo de Alta": avaliacoes/entrega8/verificacao/DECIDE/proto-alta.md             

          - "Lista de verificação dos artefatos do grupo + 1":
             - "Personas": avaliacoes/entrega8/verificacao+1/personas.md
             - "Elenco de Personas": avaliacoes/entrega8/verificacao+1/elenco-de-personas.md
             - "Cenários": avaliacoes/entrega8/verificacao+1/cenarios.md
             - "Análise de Hierárquia de Tarefas": avaliacoes/entrega8/verificacao+1/hta.md
             - "Árvores de Tarefas Concorrentes": avaliacoes/entrega8/verificacao+1/ctt.md
             - "Framework DECIDE": 
                - "Análise de Hierárquia de Tarefas": avaliacoes/entrega8/verificacao+1/DECIDE/hta.md
                - "Storyboard": avaliacoes/entrega8/verificacao+1/DECIDE/storyboard.md               
                - "Protótipo de Papel": avaliacoes/entrega8/verificacao+1/DECIDE/proto-papel.md
                - "Protótipo de Alta": avaliacoes/entrega8/verificacao+1/DECIDE/proto-alta.md

  - Atas:
      - "Atas": Atas/ata1.md

  - Apresentações:
      - "Entrega 2 e 3": apresentacoes/entrega2.md
      - "Entrega 4": apresentacoes/entrega4.md

  - Planejamento:
      - "Cronograma": planejamento/cronograma.md
      - "Sites Avaliados": planejamento/sites-avaliados.md
      - "Site Escolhido": planejamento/site-escolhido.md
      - "Processo de design": planejamento/Processo de design.md
      - "Ferramentas": planejamento/ferramentas.md
      - "Mapa de Energia": planejamento/mapa-de-energia.md

  - Análise de requisitos:
      - "Aspectos éticos": Analise-de-requisitos/aspectos-eticos.md
      - "Perfil de usuário": Analise-de-requisitos/perfil-de-usuario.md
      - "Cenários": Analise-de-requisitos/cenarios.md
      - "Personas": Analise-de-requisitos/personas.md
      - "Análise de tarefas": Analise-de-requisitos/analise-de-tarefas.md
      - "Princípios gerais de projeto": Analise-de-requisitos/principios-gerais-de-projeto.md
      - "Metas de usabilidade": Analise-de-requisitos/metas-de-usabilidade.md
      - "Guia de estilo": Analise-de-requisitos/guia-de-estilo.md
      - "Características da plataforma": Analise-de-requisitos/caracteristicas-da-plataforma.md

  - Design, Avaliação e Desenvolvimento:
      - "Nível 1":
          - " Análise de tarefas":
              - " Planejamento da avaliação da Análise de Tarefas": Design-Avaliação-Desenvolvimento/Analise/avaliacao-analise-tarefas.md
              - " Planejamento do relato dos resultados da avaliação da Análise de Tarefas": Design-Avaliação-Desenvolvimento/Analise/resultado-analise-tarefas.md
              - " Relato dos resultados da avaliação da Análise de Tarefas": Design-Avaliação-Desenvolvimento/Analise/relato-dos-resultados-analise-tarefas.md
          - " Storyboard ":
              - " Planejamento da Avaliação do Storyboard": Design-Avaliação-Desenvolvimento/Storyboard/avaliacao-storyboard.md
              - " Planejamento do relato dos resultados da avaliação do Storyboard": Design-Avaliação-Desenvolvimento/Storyboard/resultado-storyboard.md
              - " Relato dos resultados da avaliação do Storyboard": Design-Avaliação-Desenvolvimento/Storyboard/relatos-resultados-storyboard.md
              - "Storyboards": Design-Avaliação-Desenvolvimento/Storyboard/storyboards.md
      - "Nivel 2":
          - "Protótipo de papel":
              - "Planejamento da Avaliação do Protótipo de Papel": Design-Avaliação-Desenvolvimento/proto-papel/avaliacao-proto-papel.md
              - "Planejamento do Relato dos Resultado do Protótipo de Papel": Design-Avaliação-Desenvolvimento/proto-papel/plan-relato-result-proto-papel.md
              - "Resultado do Relato dos Resultado do Protótipo de Papel": Design-Avaliação-Desenvolvimento/proto-papel/relatos.md

      - "Nível 3":
          - "Protótipo de Alta Fidelidade":
              - "Planejamento da Avaliação do Protótipo de Alta Fidelidade": Design-Avaliação-Desenvolvimento/proto-alta/planejamento-avaliacao.md
              - "Planejamento do Relato dos Resultado do Protótipo de Alta Fidelidade": Design-Avaliação-Desenvolvimento/proto-alta/planejamento-resultados.md
              - "Resultado do Relato dos Resultados do Protótipo de Alta Fidelidade": Design-Avaliação-Desenvolvimento/proto-alta/resultados.md
              - "Protótipo de Alta Fidelidade": Design-Avaliação-Desenvolvimento/proto-alta/prototipo-alta.md
              
  - Entrega Final:
      - "Cinemark": Entrega-Final/cinemark.md
      - "Ciclo de vida": Entrega-Final/ciclo-de-vida.md
      - "Planejamento Recursos e Entregas": Entrega-Final/planejamento-recur-ent.md
      - "Execução do Projeto": Entrega-Final/execucao.md
      - "Resultados": Entrega-Final/resultado.md
      - "Ferramentas": Entrega-Final/ferramentas.md
      - "Técnicas": Entrega-Final/tecnicas.md
      - "Artefatos": Entrega-Final/artefatos.md
      - "Avaliações do Protótipos": Entrega-Final/avalia-prot.md
      - "Método de Verificação": Entrega-Final/metodo-verif.md
      - "Vídeos das Apresentações": Entrega-Final/video-apresenta.md
      - "Feedback": Entrega-Final/feedback.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  disable_nav_previous_next: true

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Trocar para modo escuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Trocar para modo claro

  favicon: assets/favicon.ico
  logo: assets/favicon.ico

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css: [stylesheets/extra.css]
